import React from 'react';
import { createClient } from '@/lib/supabase/server';
import { BusinessCreditPassportService } from '@/server/ai';
import { ShieldCheck, CheckCircle2, XCircle, Search } from 'lucide-react';
import Link from 'next/link';
import Image from 'next/image';

interface VerifyPageProps {
  searchParams: Promise<{ code?: string; hash?: string }>;
}

export default async function PublicCreditPassportVerifyPage({ searchParams }: VerifyPageProps) {
  const { code, hash } = await searchParams;
  const supabase = await createClient();

  let verificationResult = null;
  let verificationError = null;

  if (code) {
    try {
      verificationResult = await BusinessCreditPassportService.verifyPassport({
        supabase,
        passportCode: code.trim(),
        artifactHash: hash ? hash.trim() : undefined,
      });
    } catch (err: any) {
      verificationError = err?.message || 'Verification failed.';
    }
  }

  return (
    <div className="min-h-screen bg-[#06120E] text-white py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-2xl mx-auto space-y-8">
        {/* Brand Header */}
        <div className="flex items-center justify-between pb-6 border-b border-white/10">
          <Link href="/" className="flex items-center gap-3">
            <Image
              src="/logo-dark-horizontal.png"
              alt="NNOO Logo"
              width={110}
              height={28}
              className="object-contain"
              style={{ width: 'auto', height: 'auto' }}
            />
          </Link>
          <span className="text-xs text-white/50">Official Verification Portal</span>
        </div>

        <div className="bg-[#0A1C16] border border-white/10 rounded-2xl p-6 lg:p-8 space-y-6 shadow-xl">
          <div>
            <h1 className="text-2xl font-bold text-white">Verify NNOO Credit Passport</h1>
            <p className="text-sm text-white/60 mt-1">
              Confirm the authenticity and cryptographic integrity of an exported or shared NNOO Credit Passport.
            </p>
          </div>

          {/* Search form */}
          <form method="GET" action="/passport/verify" className="space-y-4">
            <div className="space-y-1">
              <label className="text-xs text-white/60">Passport Code</label>
              <input
                type="text"
                name="code"
                defaultValue={code || ''}
                placeholder="e.g. NNOO-CP-7F3K9Q2M"
                required
                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white font-mono placeholder:text-white/30 focus:outline-none focus:border-[#B8F25C]"
              />
            </div>

            <div className="space-y-1">
              <label className="text-xs text-white/60">Artifact Hash (Optional)</label>
              <input
                type="text"
                name="hash"
                defaultValue={hash || ''}
                placeholder="Cryptographic SHA-256 artifact hash"
                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white font-mono placeholder:text-white/30 focus:outline-none focus:border-[#B8F25C]"
              />
            </div>

            <button
              type="submit"
              className="w-full py-2.5 bg-[#B8F25C] hover:bg-[#a6db4f] text-[#0A1C16] font-semibold text-sm rounded-xl transition flex items-center justify-center gap-2"
            >
              <Search className="w-4 h-4" />
              Verify Passport
            </button>
          </form>

          {/* Verification Result Card */}
          {verificationResult && (
            <div className="p-6 bg-emerald-500/10 border border-emerald-500/20 rounded-xl space-y-4">
              <div className="flex items-center gap-3">
                <CheckCircle2 className="w-6 h-6 text-emerald-400 shrink-0" />
                <div>
                  <h3 className="text-base font-bold text-white">Authentic NNOO Credit Passport</h3>
                  <p className="text-xs text-emerald-300">
                    This snapshot was officially generated by the NNOO Business Operating System.
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4 text-xs pt-2 border-t border-emerald-500/20">
                <div>
                  <span className="text-white/50 block">Business Name</span>
                  <span className="text-white font-medium">{verificationResult.businessName}</span>
                </div>
                <div>
                  <span className="text-white/50 block">Passport Version</span>
                  <span className="text-white font-medium">Version {verificationResult.passportVersion}</span>
                </div>
                <div>
                  <span className="text-white/50 block">Generated Date</span>
                  <span className="text-white font-medium">
                    {new Date(verificationResult.generatedAt).toLocaleString()}
                  </span>
                </div>
                <div>
                  <span className="text-white/50 block">Integrity Status</span>
                  <span className="text-emerald-400 font-semibold">
                    {verificationResult.isIntegrityVerified ? 'Tamper Check Passed' : 'Hash Mismatch'}
                  </span>
                </div>
              </div>
            </div>
          )}

          {verificationError && (
            <div className="p-6 bg-rose-500/10 border border-rose-500/20 rounded-xl flex items-center gap-3">
              <XCircle className="w-6 h-6 text-rose-400 shrink-0" />
              <div>
                <h3 className="text-base font-bold text-white">Verification Failed</h3>
                <p className="text-xs text-rose-300">{verificationError}</p>
              </div>
            </div>
          )}
        </div>

        {/* Disclaimer */}
        <div className="p-4 bg-white/5 border border-white/10 rounded-xl text-center text-xs text-white/50">
          Verification confirms only that the Credit Passport snapshot matches records generated in NNOO. It is not an independent financial audit or a credit score.
        </div>
      </div>
    </div>
  );
}
